name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release-linux:
    name: Release Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e970a256a29d67566144e5f760e1d88045 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Fetch Embedded MPV
        run: |
          bash scripts/fetch-mpv.sh --linux

      - name: Build Linux Binary
        run: |
          make build

      - name: Upload Linux Release Asset
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: jellyfin-tui-linux-amd64
          path: bin/jellyfin-tui
          if-no-files-found: error
          retention-days: 30

  release-windows:
    name: Release Windows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e970a256a29d67566144e5f760e1d88045 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Fetch Embedded MPV
        run: |
          bash scripts/fetch-mpv.sh --windows

      - name: Build Windows Binary
        run: |
          make windows

      - name: Upload Windows Release Asset
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: jellyfin-tui-windows-amd64
          path: bin/jellyfin-tui.exe
          if-no-files-found: error
          retention-days: 30

  publish:
    name: Publish Release
    needs:
      - release-linux
      - release-windows
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux Binary
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: jellyfin-tui-linux-amd64
          path: dist

      - name: Download Windows Binary
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: jellyfin-tui-windows-amd64
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@fe965f7af51af5f2602596916f38a38df2e33de0 # v3.0.2
        with:
          files: |
            dist/jellyfin-tui
            dist/jellyfin-tui.exe
          generate_release_notes: true
