name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release-linux:
    name: Release Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Fetch Embedded MPV
        run: |
          bash scripts/fetch-mpv.sh --linux

      - name: Build Linux Binary
        run: |
          make build

      - name: Upload Linux Release Asset
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: jellyfin-tui-linux-amd64
          path: bin/jellyfin-tui
          if-no-files-found: error
          retention-days: 30

  release-windows:
    name: Release Windows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Fetch Embedded MPV
        run: |
          bash scripts/fetch-mpv.sh --windows

      - name: Build Windows Binary
        run: |
          make windows

      - name: Upload Windows Release Asset
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: jellyfin-tui-windows-amd64
          path: bin/jellyfin-tui.exe
          if-no-files-found: error
          retention-days: 30

  publish:
    name: Publish Release
    needs:
      - release-linux
      - release-windows
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux Binary
        uses: actions/download-artifact@d3f86a106a0bac45b584ad529006beecc3defe12 # v4.3.0
        with:
          name: jellyfin-tui-linux-amd64
          path: dist

      - name: Download Windows Binary
        uses: actions/download-artifact@d3f86a106a0bac45b584ad529006beecc3defe12 # v4.3.0
        with:
          name: jellyfin-tui-windows-amd64
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@a74a6ed8d47435309b97e4d3e2f4e74d1e941650 # v2.0.1
        with:
          files: |
            dist/jellyfin-tui
            dist/jellyfin-tui.exe
          generate_release_notes: true
